language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  - pip install -q coveralls --use-mirrors
  - pip install -q -e . --use-mirrors

script:
  - coverage run --source=timecodes setup.py test

after_success:
  - coveralls
